Media Footage: https://media.ccc.de/b/congress/2015

Schedule: https://events.ccc.de/congress/2015/Fahrplan/schedule/0.html

* What does Big Brother see, while he is watching?
- https://events.ccc.de/congress/2015/Fahrplan/events/7209.html
- http://c3media.vsos.ethz.ch/congress/2015/h264-hd/32c3-7209-en-What_does_Big_Brother_see_while_he_is_watching_hd.mp4

** Alain

Simon Menner shows a great collection of pictures from the best
treasure trove that is accessible to us from surveillance
states. He tells a good story on how absurd and dangerous surveillance
is at the same time.

It's also curious to hear that only footage from eastern countries is
available, the BND only released 14 totally irrelevant pictures of all
of the cold war (something like a cork screw...). So of course the
easter states totally look illegal compared to just nothing.

* Beyond your cable modem 
- https://events.ccc.de/congress/2015/Fahrplan/events/7133.html
- https://media.ccc.de/v/32c3-7133-beyond_your_cable_modem#video

** Alain
Very fun and at the same time horrific talk. Basically everyone
on a cable network can easily gain access to a root shell on everyone
elses cable modem. Not only that, you can also listen in to other
peoples VOIP calls or call from somebody eleses number.

Horrifying, because it's so simple and extremely powerful.

In the questions, it's also very interesting at 30:15 when he's being
asked an easy question and the guy gets very uneasy and says: "The
problem is the law. I cannot tell you about ....".

* Netzpolitik in der Schweiz
- https://events.ccc.de/congress/2015/Fahrplan/events/7205.html
- https://media.ccc.de/v/32c3-7205-netzpolitik_in_der_schweiz_2015_16#video&t=1779

** Alain

Sehr langweilig vorgetragen. Die Sprecher nutzen gerne Wörter und
Akronyme rechtlicher Natur ohne sie einzuführen oder zu
erklären. Primär eine Erklärung des aktuellen Stands und den neuen
Gesetzen, die alsbald kommen können. Dahingehend inhaltlich durchaus
interessant.

** Max

Gibt einen guten Überblick über die Möglichkeiten zur politischen Partizipation in der Schweiz und versch. Überwachungsgesetze. 
Ist zum teil anstrengend zu folgen, das die Vortragenden den guten Stoff nicht besonders aufarbeiten.

* Internet Landscapes 
- https://events.ccc.de/congress/2015/Fahrplan/events/7412.html
- https://media.ccc.de/v/32c3-7538-internet_landscapes#video&t=1957

** Alain
An artists view into the Internet and the emerging Internet
culture. Interesting concepts on how to visualize the un-seeable.

No tangible value, however an artistic talk that I enjoyed.

* NSA-Untersuchungsausschuss: Zwischen Aufklärungswillen und Mauern aus Schweigen
https://events.ccc.de/congress/2015/Fahrplan/events/7228.html

** Max
Bei Interesse an der deutschen Aufarbeitung von 5-Eyes etc. super spannend.
Aus schweizer Sicht wohl eher nicht sooo sehr.

* PQCHacks - A gentle introduction to post-quantum cryptography
https://events.ccc.de/congress/2015/Fahrplan/events/7210.html

** Max
Super spannender Vortrag von zwei Koryphäen auf dem Bereich. Es braucht zwei
etwa zwei Stunden Konzentration sollte aber mit einem grundlegenden Interesse
an der Materie gut verständlich sein.

* Shopshifting - The potential for payment system abuse
https://events.ccc.de/congress/2015/Fahrplan/events/7368.html

** Max
Deutsche EC-Karten (Maestro Äquivalent) Terminals sind auf mehreren Leveln vollkommen kaputt.
Der Talk zeigt (grösstenteils) super Aufbereitet wie man die verwendeten Sicherheitslücken zum Schaden von Kunden und Händlern ausnutzen kann und was falsch lief.

* Running your own 3G/3.5G network
https://events.ccc.de/congress/2015/Fahrplan/events/7412.html

** Max
Trocken. Sehr sehr Trocken. Sicher spannend für Experten und der Typ kennt sich aus ... nix für Leute, die mit der Materie nicht vertraut sind.

* How the Great Firewall discovers hidden circumvention servers
https://events.ccc.de/congress/2015/Fahrplan/events/7196.html

** Max
Spannende Einblicke in die Funktionsweise der great Firewall, die Auswirkungen und was dies Allgemein für Zensur bedeuten kann.

** Ein Abgrund von Landesverat
https://events.ccc.de/congress/2015/Fahrplan/events/7135.html

** Max
Die Landesverat Ermitlungen gegen das Blog netzpolitik.org haben im Sommer 2015 für einige Aufregung in Deutschland gesorgt. 
Der Talk ist eine humoristische Aufarbeitung der Erkenntnisse. 

* Lifting the Fog on Red Star OS

** Max
Hat ein rechtes Medienecho erhalten. Klingt noch spannend...

* Das Zahnrad aus Fleisch
https://events.ccc.de/congress/2015/Fahrplan/events/7249.html

** Max
Spannendes Thema, einige Highlights (originale Kommentare etc.) leider von vielen Allgemeinplätzen umgeben und deshalb nicht wirklich sehenswert.

* goto fail;
https://events.ccc.de/congress/2015/Fahrplan/events/7438.html

** Max
Bester Talk über SSL/TLS den ich je gehört habe.
Guter Überblick über Funktionsweise und über diverse Angriffe.