Media Footage: https://media.ccc.de/b/congress/2015

Schedule: https://events.ccc.de/congress/2015/Fahrplan/schedule/0.html

* Media overview
Day 1: https://netzpolitik.org/2015/netzrueckblick-32c3-der-erste-tag/

Day 2: http://np.vu/n/109710

* What does Big Brother see, while he is watching?
- https://events.ccc.de/congress/2015/Fahrplan/events/7209.html
- http://c3media.vsos.ethz.ch/congress/2015/h264-hd/32c3-7209-en-What_does_Big_Brother_see_while_he_is_watching_hd.mp4

** Alain

Simon Menner shows a great collection of pictures from the best
treasure trove that is accessible to us from surveillance
states. He tells a good story on how absurd and dangerous surveillance
is at the same time.

It's also curious to hear that only footage from eastern countries is
available, the BND only released 14 totally irrelevant pictures of all
of the cold war (something like a cork screw...). So of course the
easter states totally look illegal compared to just nothing.

* Beyond your cable modem 
- https://events.ccc.de/congress/2015/Fahrplan/events/7133.html
- https://media.ccc.de/v/32c3-7133-beyond_your_cable_modem#video

** Alain
Very fun and at the same time horrific talk. Basically everyone
on a cable network can easily gain access to a root shell on everyone
elses cable modem. Not only that, you can also listen in to other
peoples VOIP calls or call from somebody eleses number.

Horrifying, because it's so simple and extremely powerful.

In the questions, it's also very interesting at 30:15 when he's being
asked an easy question and the guy gets very uneasy and says: "The
problem is the law. I cannot tell you about ....".

* Netzpolitik in der Schweiz
- https://events.ccc.de/congress/2015/Fahrplan/events/7205.html
- https://media.ccc.de/v/32c3-7205-netzpolitik_in_der_schweiz_2015_16#video&t=1779

** Alain

Sehr langweilig vorgetragen. Die Sprecher nutzen gerne Wörter und
Akronyme rechtlicher Natur ohne sie einzuführen oder zu
erklären. Primär eine Erklärung des aktuellen Stands und den neuen
Gesetzen, die alsbald kommen können. Dahingehend inhaltlich durchaus
interessant.

** Max

Gibt einen guten Überblick über die Möglichkeiten zur politischen Partizipation in der Schweiz und versch. Überwachungsgesetze. 
Ist zum teil anstrengend zu folgen, das die Vortragenden den guten Stoff nicht besonders aufarbeiten.

* Internet Landscapes 
- https://events.ccc.de/congress/2015/Fahrplan/events/7412.html
- https://media.ccc.de/v/32c3-7538-internet_landscapes#video&t=1957

** Alain
An artists view into the Internet and the emerging Internet
culture. Interesting concepts on how to visualize the un-seeable.

No tangible value, however an artistic talk that I enjoyed.

* NSA-Untersuchungsausschuss: Zwischen Aufklärungswillen und Mauern aus Schweigen
https://events.ccc.de/congress/2015/Fahrplan/events/7228.html

** Max
Bei Interesse an der deutschen Aufarbeitung von 5-Eyes etc. super spannend.
Aus schweizer Sicht wohl eher nicht sooo sehr.

* PQCHacks - A gentle introduction to post-quantum cryptography
https://events.ccc.de/congress/2015/Fahrplan/events/7210.html

** Max
Super spannender Vortrag von zwei Koryphäen auf dem Bereich. Es braucht zwei
etwa zwei Stunden Konzentration sollte aber mit einem grundlegenden Interesse
an der Materie gut verständlich sein.

* Shopshifting - The potential for payment system abuse
https://events.ccc.de/congress/2015/Fahrplan/events/7368.html

** Max
Deutsche EC-Karten (Maestro Äquivalent) Terminals sind auf mehreren Leveln vollkommen kaputt.
Der Talk zeigt (grösstenteils) super Aufbereitet wie man die verwendeten Sicherheitslücken zum Schaden von Kunden und Händlern ausnutzen kann und was falsch lief.

* Running your own 3G/3.5G network
https://events.ccc.de/congress/2015/Fahrplan/events/7412.html

** Max
Trocken. Sehr sehr Trocken. Sicher spannend für Experten und der Typ kennt sich aus ... nix für Leute, die mit der Materie nicht vertraut sind.

* How the Great Firewall discovers hidden circumvention servers
https://events.ccc.de/congress/2015/Fahrplan/events/7196.html

** Max
Spannende Einblicke in die Funktionsweise der great Firewall, die Auswirkungen und was dies Allgemein für Zensur bedeuten kann.

* Ein Abgrund von Landesverat
https://events.ccc.de/congress/2015/Fahrplan/events/7135.html

** Max
Die Landesverat Ermitlungen gegen das Blog netzpolitik.org haben im Sommer 2015 für einige Aufregung in Deutschland gesorgt. 
Der Talk ist eine humoristische Aufarbeitung der Erkenntnisse. 
Eher ein post mortem da bspw. auf dem Camp 2015 das Thema schon gross debattiert wurde.

* Profiling (In)justice
'https://events.ccc.de/congress/2015/Fahrplan/events/7264.html' 

** Max 
Wurde mir empfohlen - will ich mal noch sehen.

* Lifting the Fog on Red Star OS

** Max
Hat ein rechtes Medienecho erhalten. Klingt noch spannend...

* Das Zahnrad aus Fleisch
https://events.ccc.de/congress/2015/Fahrplan/events/7249.html

** Max
Gutes Thema, einige Highlights (originale Kommentare etc.) leider von vielen Allgemeinplätzen umgeben und deshalb nicht wirklich sehenswert.

* goto fail;
https://events.ccc.de/congress/2015/Fahrplan/events/7438.html

** Max
Bester Talk über SSL/TLS den ich bisher gehört habe.
Guter Überblick über Funktionsweise und über diverse Angriffe.

* Unpatchable - living with a vulnerable implanted device 
https://events.ccc.de/congress/2015/Fahrplan/events/7273.html

** Max
Intensives Echo in Medien und sozialen Netzwerken - will ich definitiv noch sehen.

* The Ultimate Amiga 500 Talk
- https://media.ccc.de/v/32c3-7468-the_ultimate_amiga_500_talk

** Alain

I was able to watch maybe the first ten minutes and then started
scrolling to the end. The end was like the talk, abrupt and no
clapping. At least there was one question...

If you want a history lesson, go for it. But be prepared for some
history boredom.

* „Nach bestem Wissen und Gewissen“ – Floskeln in der Politik 

** Max
Ganz nette Aufsführungen zu Sprache und mit ihr verbundem oder eben auch nicht verbundenem Informationsgehalt.
An einigen stellen gefühlt eher esoterisch und wichtige Aspekte der politischen Rede vernachlässigend.
Ein grobes Wissen über wichtige Themen der dt. Politik in 2015 wird benötigt.

* Graphs, Drones & Phones - The role of social-graphs for Drones in the War on Terror. 

** Max
Übel. Ganz übel. Sehr sehenswerte Ausführungen wie ein bisschen Graphentheorie zum Abschuss von Hellfire-Raketen und Co. führt und wie wir auch sonst alle nur Knoten mit mehr oder weniger Kanten sind. Stimmt eher nachdenklich - gelinde gesagt.


* State of the Onion

** Max
Alle Jahre wieder. Das Tor Team schwört eine Begeisterte Menge von > 2000 Nerds auf Freiheit und Anonymisierung ein. Indoktrinierung für die verschiedenen Werte. Besonders spannend: eine radikale, militante Bibliothekarin erzählt mitreissend über den Einstieg von US-Amerikanischen Bibliothekaren in die Anonymisierungsszene.

* Check your privileges!

** Max
Sehr technischer, fundierter Talk wie man auf system programming level Applikationen möglichst sicher machen kann. 
Hinreichende Kentnisse in C werden implizit vorausgesetzt. Folien lesen lohnt sich ;).


* Ten years after ‚We Lost The War‘

** Max
Wir haben den Krieg verloren, die Revolution wird kommen - warum und was können wir machen um unsere individuellen Leben dennoch angenhm zu gestalten? 
In Teilen sehr dystopisch aber eventuell motivierend sich auf die Mitmenschen und das was wirklich zählt zu besinnen? Stimmt sehr nachdenklich - keine gute Idee für einsame Abende.

* Computational Meta Psychology (Joscha Bach)

** Tomaso
Nachdenken darüber wie wir auf den Ebenen unter der Psyche funktionieren, wie wir lernen. Empfohlen.
